### ISSUE TITLE
Fails to deploy when SSH Key is used in VSI in EPX project deployment

### ISSUE THREAD

**Issue by jpapejr** [terraform-ibm-modules/terraform-ibm-landing-zone#425] opened 2023-04-28 15:39 UTC
### Affected modules

virtual_servers.tf

### Terraform CLI and Terraform provider versions

* Terraform version: terraform1.3
* Provider version: ibm-cloud/ibm v1.49.0 (self-signed, key ID AAD3B791C49CC253)

### Terraform output

https://github.ibm.com/jtpape/epx-experiments#tf-bug-in-vsi-module

### Expected behavior

The project deployment should have included my VSI with the specified SSH key configured for access. 

### Actual behavior

Terraform deployment fails and project is not deployed successfully

### Steps to reproduce (including links and screen captures)

1. Create EPX project on IBM Cloud
2. Add configuration for VPC ROKS LZ
3. Use SLZ GUI to produce JSON for override.json
4. Use override in configuration and deploy configuration
5. See failure with log output at link posted above. 

### Anything else

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by ocofaigh** [comment] 2023-05-04 14:27
Thanks for reporting. The root cause to this issue is a known issue, and we are working on a fix now.

**Comment by ocofaigh** [comment] 2023-05-17 10:19
This was fixed in https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/releases/tag/v3.8.1
We will be publishing a new version of the DA to catalog this week which has this fix

**Comment by ocofaigh** [comment] 2023-05-24 13:54
https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/releases/tag/v3.8.0 actually has the fix for this (see details in release notes). We have published version 3.8.3 to the catalog which will also have this fix. Going to close this issue. If any issues, please re-open

**Closed by ocofaigh** 2023-05-24 13:54 UTC
Labels: bug 🐞
