### ISSUE TITLE
Wait until ingress is ready

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-landing-zone#747] opened 2024-03-19 21:26 UTC
### Description

Some reports that clusters are not fully ready after install https://github.com/terraform-ibm-modules/terraform-ibm-mas/issues/24

There is already a condition at https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/blob/a28231d1d8e972f7525375d5b717f206bb2aa00d/variables.tf#L909

Possibly porting https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/blob/404cb937a0d9f9e558c77c8852a5f88b3ff21d84/main.tf#L383 may be sufficient, to investigate.

### New or affected modules

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by ocofaigh** [comment] 2024-03-22 12:04
In order to run the script at https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/blob/404cb937a0d9f9e558c77c8852a5f88b3ff21d84/main.tf#L383 in landing zone you would need access to the private network to be able to connect to cluster with kubectl since public endpoint is disabled by default. There may also be other network restrictions in place that might block that connection?

**Comment by ocofaigh** [comment] 2024-05-08 08:38
We think think this is why many of the tests used in the MAS PR test pipeline fail intermittently too - seems the cluster is not fully ready.

**Comment by ocofaigh** [comment] 2024-05-09 09:28
I do believe we can easily recreate this. Even after the cluster ingress goes green, the master seems to then get restarted to confirue KMS encryption:
![image](https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/assets/29608224/c61a3b01-219e-448c-842a-9b2443147f6b)
![image](https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/assets/29608224/a7be11a6-0fbf-44ff-8573-19e6fbb847c1)

After reaching out to IKS, this seems to be a known issue:

> ROKS version 4.14 and later will see various API services fail discovery during a restart of the Kubernetes API server restart.

There is an internal issue tracking this with IKS: https://github.ibm.com/alchemy-containers/armada-network/issues/8843

Meanwhile, perhaps we could add extra checks on the master status AFTER the ingress has gone green?

**Comment by ocofaigh** [comment] 2024-05-09 13:57
I tried running the [confirm_network_healthy.sh](https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/blob/404cb937a0d9f9e558c77c8852a5f88b3ff21d84/scripts/confirm_network_healthy.sh) script but it didn't help. The Ingress is green and the script passed after 2 seconds however the master status was "Key management service enablement in progress". 
I think `ibm_container_vpc_cluster` will need to be updated so there is a new option for `wait_till` to return after masters have been updated after Key management service enablement is complete.
I have raised an IKS support case

**Comment by ocofaigh** [comment] 2024-05-14 11:43
Things seem alot better in OCP 4.14. They fixed the issue I quoted [above](https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/issues/747#issuecomment-2102296421) and confirmed the following:

> So, if this happened during KMS update, it might have failed attempting to create the redhat-marketplace namespace, because openshift-pipelines has an admission webhook for namespaces.  If the cluster is 4.13 or earlier we know there is a large window during a master update (kms, patch update,master refresh, etc) - at one point around 10 minutes - where webhooks, aggregated APIs, exec and logs requests, etc will randomly fail.
> That's a fact of life for 4.13 and earlier (which use an OpenVPN tunnel) and why 4.14 and later use Konnectivity.

**Comment by ocofaigh** [comment] 2024-05-23 20:18
This might help:

> our internal team has found the following:
> the terraform plugin has a new field in kms_config called `wait_for_apply`, it is a bool.
> If set to true, terraform will wait until the KMS is applied to the master, ready and deployed.

Going to test it out

**Comment by ocofaigh** [comment] 2024-07-17 13:07
The fix for this was added in https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/releases/tag/v5.25.0

**Closed by ocofaigh** 2024-07-17 13:07 UTC
Labels: bug 🐞, internal-synced
